CS280S14: ObjectAllocator Class Reference
ObjectAllocator Class Reference
The Object Allocator (Memory manager).
#include <ObjectAllocator.h>
Public Types
typedef void(* DUMPCALLBACK)(const void *, size_t)
Defined by the client (pointer to a block, size of block).
typedef void(* VALIDATECALLBACK)(const void *, size_t)
Defined by the client (pointer to a block, size of block).
Public Member Functions
ObjectAllocator (size_t ObjectSize, const OAConfig &config) throw (OAException)
Destroys the ObjectManager (never throws).
~ObjectAllocator () throw ()
Passes the client a block of memory.
void * Allocate (const char *label=0) throw (OAException)
Frees allocated memory.
void Free (void *Object) throw (OAException)
Calls the callback fn for each block still in use.
unsigned DumpMemoryInUse (DUMPCALLBACK fn) const
Calls the callback fn for each block that is potentially corrupted.
unsigned ValidatePages (VALIDATECALLBACK fn) const
Frees all empty pages (extra credit).
unsigned FreeEmptyPages (void)
Returns true if FreeEmptyPages and alignments are implemented.
void SetDebugState (bool State)
< Sets the debugging state
const void * GetFreeList (void) const
Returns pointer to page list.
const void * GetPageList (void) const
Returns config info.
OAConfig GetConfig (void) const
Returns stats info.
OAStats GetStats (void) const
Returns the stats of the ObjectAllocator.
Static Public Member Functions
static bool ImplementedExtraCredit (void)
Returns true if FreeEmptyPages and alignments are implemented.
Static Public Attributes
static const unsigned char UNALLOCATED_PATTERN = 0xAA
Unallocated.
static const unsigned char ALLOCATED_PATTERN = 0xBB
Allocated.
static const unsigned char FREED_PATTERN = 0xCC
Freed.
static const unsigned char PAD_PATTERN = 0xDD
Padding.
static const unsigned char ALIGN_PATTERN = 0xEE
Alignment.
Private Member Functions
ObjectAllocator (const ObjectAllocator &oa)
< No copy construction
ObjectAllocator & operator= (const ObjectAllocator &oa)
void CheckInFreeList (GenericObject *theObj) const throw (OAException)
< Check whether the object is in the free list, throw exceptions if it is
void CheckPadding (GenericObject *theObj) const throw (OAException)
Check whether the object is on the boundary, throw exceptions if not.
void CheckOnBoundary (GenericObject *theObj) const throw (OAException)
Checks whether the object is on the boundary, throws exceptions if it is not (the pointer is not pointing to the data block's start).
GenericObject * AddPage () throw (OAException)
< Allocates a new page and sets it up, returns pointer to new page
void FreePage (GenericObject *thePagePtr)
Just returns the data portion which belongs to the header.
GenericObject * GetDataPtr (GenericObject *theHeader) const
Just returns the pointer to the first header in the list.
GenericObject * GetFirstHeader (GenericObject *theList) const
Just returns the pointer to the next header in the list.
GenericObject * GetNextHeader (GenericObject *prevHdr) const
Returns whether its an empty page (Non-HeaderNone version).
bool IsEmptyPage_Header (GenericObject *pagePtr) const
Returns whether it is an empty page (HeaderNone version).
bool IsEmptyPage_NoHeader (GenericObject *pagePtr) const
Returns the size of a page based on the config (Modifies the config).
size_t GetPageSize (size_t ObjectSize, OAConfig &config) const
Returns the size of a page based on the config and modifies the config file accordingly.
GenericObject * PopFront () throw (OAException)
< Grabs the first mem block from the front of the free list and returns
void PushFront (GenericObject *memBlock)
Adds the memory block to the front of the free list.
Private Attributes
OAConfig _config
The configuration options.
OAStats _stats
The current statistics.
GenericObject * _freeList
The free list.
GenericObject * _pageList
The page list.
Detailed Description
The Object Allocator (Memory manager).
Definition at line 346 of file ObjectAllocator.h.
Member Typedef Documentation
typedef void(* ObjectAllocator::DUMPCALLBACK)(const void *, size_t)
Defined by the client (pointer to a block, size of block).
typedef void(* ObjectAllocator::VALIDATECALLBACK)(const void *, size_t)
Defined by the client (pointer to a block, size of block).
Constructor & Destructor Documentation
ObjectAllocator::ObjectAllocator (size_t ObjectSize, const OAConfig & config) throw (OAException)
Destroys the ObjectManager (never throws).
Creates the ObjectManager per the specified values. Throws an exception if the construction fails. (Memory allocation problem).
Parameters:
[in] ObjectSize The size of each object.
[in] config The configuration of the ObjectAllocator
Definition at line 366 of file ObjectAllocator.cpp.
ObjectAllocator::~ObjectAllocator () throw ()
Passes the client a block of memory.
Destroys the ObjectManager (never throws).
Definition at line 388 of file ObjectAllocator.cpp.
References _pageList, FreePage(), and GenericObject::Next.
ObjectAllocator::ObjectAllocator (const ObjectAllocator & oa) [private]
< No copy construction
No assignment
Member Function Documentation
GenericObject * ObjectAllocator::AddPage () throw (OAException) [private]
< Allocates a new page and sets it up, returns pointer to new page
Allocates a new page and sets it up, along with returning a pointer to the new page (modifies data).
Frees the page
Returns:
The new page
Definition at line 982 of file ObjectAllocator.cpp.
References _config, _stats, ALIGN_PATTERN, OAConfig::DebugOn_, OAException::E_NO_MEMORY, OAException::E_NO_PAGES, OAConfig::HBlockInfo_, OAConfig::InterAlignSize_, OAConfig::LeftAlignSize_, OAConfig::MaxPages_, OAStats::ObjectSize_, OAConfig::ObjectsPerPage_, PAD_PATTERN, OAConfig::PadBytes_, OAStats::PagesInUse_, OAStats::PageSize_, PushFront(), and UNALLOCATED_PATTERN.
void * ObjectAllocator::Allocate (const char * label = 0) throw (OAException)
Frees allocated memory.
Take an object from the free list and give it to the client (simulates new) Throws an exception if the object can't be allocated. (Memory allocation problem).
Parameters:
[in] label The label to set for the External header (if it is External Header)
Returns:
The pointer to the allocated memory.
Definition at line 415 of file ObjectAllocator.cpp.
References OAException::E_NO_MEMORY, OAConfig::hbExtended, OAConfig::hbExternal, OAConfig::hbNone, and GenericObject::Next.
void ObjectAllocator::CheckInFreeList (GenericObject * theObj) const throw (OAException) [private]
< Check whether the object is in the free list, throw exceptions if it is
Checks whether the object is in the free list, throws exceptions if it is. (Not supposed to be in free list) Does so manually.
Checks the padding of the object, throws exceptions if it is corrupted
Parameters:
[in] theObj The object to check whether it is within the free list
Definition at line 817 of file ObjectAllocator.cpp.
References OAException::E_MULTIPLE_FREE, and GenericObject::Next.
void ObjectAllocator::CheckOnBoundary (GenericObject * theObj) const throw (OAException) [private]
Checks whether the object is on the boundary, throws exceptions if it is not (the pointer is not pointing to the data block's start).
Parameters:
[in] theObj The object to check the padding of
Definition at line 871 of file ObjectAllocator.cpp.
References OAException::E_BAD_BOUNDARY, and GenericObject::Next.
void ObjectAllocator::CheckPadding (GenericObject * theObj) const throw (OAException) [private]
Check whether the object is on the boundary, throw exceptions if not.
Checks the padding of the object, throws exceptions if it is corrupted.
Parameters:
[in] theObj The object to check the padding of
Definition at line 838 of file ObjectAllocator.cpp.
References OAException::E_CORRUPTED_BLOCK.
unsigned ObjectAllocator::DumpMemoryInUse (DUMPCALLBACK fn) const
Calls the callback fn for each block that is potentially corrupted.
Calls the callback fn for each block still in use.
Parameters:
[in] fn The callback function to use on each block. void (*)(const void *, size_t)
Returns:
The number of memory blocks still in use
Definition at line 550 of file ObjectAllocator.cpp.
References _config, _freeList, _pageList, _stats, GetDataPtr(), GetFirstHeader(), GetNextHeader(), OAConfig::hbBasic, OAConfig::hbExtended, OAConfig::hbExternal, OAConfig::HBlockInfo_, OAConfig::hbNone, MemBlockInfo::in_use, GenericObject::Next, OAStats::ObjectSize_, OAConfig::ObjectsPerPage_, and OAConfig::PadBytes_.
void ObjectAllocator::Free (void * Object) throw (OAException)
Calls the callback fn for each block still in use.
Returns an object to the free list for the client (simulates delete) Throws an exception if the the object can't be freed. (Invalid object).
Parameters:
[in] Object The object to free
Definition at line 479 of file ObjectAllocator.cpp.
References OAException::E_MULTIPLE_FREE, OAConfig::hbBasic, OAConfig::hbExtended, OAConfig::hbExternal, OAConfig::hbNone, and MemBlockInfo::in_use.
unsigned ObjectAllocator::FreeEmptyPages (void)
Returns true if FreeEmptyPages and alignments are implemented.
Frees all empty pages.
Returns:
The amount of pages freed.
Definition at line 679 of file ObjectAllocator.cpp.
References _config, _pageList, _stats, OAStats::FreeObjects_, FreePage(), OAConfig::HBlockInfo_, OAConfig::hbNone, IsEmptyPage_Header(), IsEmptyPage_NoHeader(), GenericObject::Next, and OAConfig::ObjectsPerPage_.
void ObjectAllocator::FreePage (GenericObject * thePagePtr) [private]
Just returns the data portion which belongs to the header.
Frees the entire page and removes all items in the free list which belong to that page.
Parameters:
[in] thePagePtr The page to free
Definition at line 1058 of file ObjectAllocator.cpp.
References _config, _freeList, _stats, OAStats::FreeObjects_, OAConfig::hbExternal, OAConfig::HBlockInfo_, OAConfig::InterAlignSize_, OAConfig::LeftAlignSize_, GenericObject::Next, OAStats::ObjectSize_, OAConfig::ObjectsPerPage_, OAConfig::PadBytes_, OAStats::PagesInUse_, and OAStats::PageSize_.
Referenced by FreeEmptyPages(), and ~ObjectAllocator().
OAConfig ObjectAllocator::GetConfig (void) const
Returns stats info.
Returns the configuration parameters.
Returns:
The configuration parameters
Definition at line 785 of file ObjectAllocator.cpp.
References _config.
GenericObject * ObjectAllocator::GetDataPtr (GenericObject * theHeader) const [private]
Just returns the pointer to the first header in the list.
Just returns the data portion which belongs to the header DOES NOT CHECK FOR NULLPTRS.
Parameters:
[in] theHeader The header to grab the data portion of
Returns:
The pointer to the data portion
Definition at line 929 of file ObjectAllocator.cpp.
References _config, OAConfig::HBlockInfo_, and OAConfig::PadBytes_.
Referenced by DumpMemoryInUse(), IsEmptyPage_Header(), and ValidatePages().
GenericObject * ObjectAllocator::GetFirstHeader (GenericObject * theList) const [private]
Just returns the pointer to the next header in the list.
Just returns the pointer to the first header in the list. DOES NOT CHECK FOR NULLPTRS.
Parameters:
[in] theList The list to get the first header of
Returns:
The pointer to the first header
Definition at line 947 of file ObjectAllocator.cpp.
References _config, and OAConfig::LeftAlignSize_.
Referenced by DumpMemoryInUse(), IsEmptyPage_Header(), and ValidatePages().
const void * ObjectAllocator::GetFreeList (void) const
Returns pointer to page list.
Returns a pointer to the internal free list.
Returns:
Pointer to the free list
Definition at line 757 of file ObjectAllocator.cpp.
References _freeList.
GenericObject * ObjectAllocator::GetNextHeader (GenericObject * prevHdr) const [private]
Returns whether its an empty page (Non-HeaderNone version).
Just returns the pointer to the next header in the list. DOES NOT CHECK FOR NULLPTRS.
Parameters:
[in] prevHdr The header to grab the next of
Returns:
The pointer to the next header
Definition at line 965 of file ObjectAllocator.cpp.
References _config, _stats, OAConfig::HBlockInfo_, OAConfig::InterAlignSize_, OAStats::ObjectSize_, and OAConfig::PadBytes_.
Referenced by DumpMemoryInUse(), IsEmptyPage_Header(), and ValidatePages().
const void * ObjectAllocator::GetPageList (void) const
Returns config info.
Returns a pointer to the internal page list.
Returns:
Pointer to the page list
Definition at line 771 of file ObjectAllocator.cpp.
References _pageList.
size_t ObjectAllocator::GetPageSize (size_t ObjectSize, OAConfig & config) const [private]
Returns the size of a page based on the config and modifies the config file accordingly.
Parameters:
[in] ObjectSize The size of each object
[in] config The configurations to modify
Returns:
The size of the page
Definition at line 1124 of file ObjectAllocator.cpp.
References OAConfig::Alignment_, OAConfig::HBlockInfo_, OAConfig::InterAlignSize_, OAConfig::LeftAlignSize_, OAConfig::ObjectsPerPage_, and OAConfig::PadBytes_.
OAStats ObjectAllocator::GetStats (void) const
Returns the stats of the ObjectAllocator.
Returns:
The stats
Definition at line 799 of file ObjectAllocator.cpp.
References _stats.
bool ObjectAllocator::ImplementedExtraCredit (void) [static]
Returns true if FreeEmptyPages and alignments are implemented.
Returns:
Whether extra credit has been implemented
Definition at line 728 of file ObjectAllocator.cpp.
bool ObjectAllocator::IsEmptyPage_Header (GenericObject * pagePtr) const [private]
Returns whether it is an empty page (HeaderNone version).
Returns whether its an empty page (If they have headers).
Parameters:
[in] pagePtr The callback function to use on each potentially corrupted block. void (*)(const void *, size_t)
Returns:
Whether it is empty or not.
Definition at line 1165 of file ObjectAllocator.cpp.
References _config, GetDataPtr(), GetFirstHeader(), GetNextHeader(), OAConfig::hbBasic, OAConfig::hbExtended, OAConfig::hbExternal, OAConfig::HBlockInfo_, MemBlockInfo::in_use, OAConfig::ObjectsPerPage_, and OAConfig::PadBytes_.
Referenced by FreeEmptyPages().
bool ObjectAllocator::IsEmptyPage_NoHeader (GenericObject * pagePtr) const [private]
Returns the size of a page based on the config (Modifies the config).
Returns whether its an empty page (If they have NO headers).
Parameters:
[in] pagePtr The callback function to use on each potentially corrupted block. void (*)(const void *, size_t)
Returns:
Whether it is empty or not.
Definition at line 1205 of file ObjectAllocator.cpp.
References _config, _freeList, _stats, GenericObject::Next, OAConfig::ObjectsPerPage_, and OAStats::PageSize_.
Referenced by FreeEmptyPages().
ObjectAllocator& ObjectAllocator::operator= (const ObjectAllocator & oa) [private]
GenericObject * ObjectAllocator::PopFront () throw (OAException) [private]
< Grabs the first mem block from the front of the free list and returns
Grabs the first mem block from the front of the free list and returns.
Adds the memory block to the front of the free list
Returns:
The first mem block
Definition at line 1236 of file ObjectAllocator.cpp.
References _freeList, _stats, OAException::E_NO_MEMORY, OAStats::FreeObjects_, and GenericObject::Next.
void ObjectAllocator::PushFront (GenericObject * memBlock) [private]
Adds the memory block to the front of the free list.
Parameters:
[in] memBlock The memory block to add
Definition at line 1259 of file ObjectAllocator.cpp.
References _freeList, _stats, OAStats::FreeObjects_, and GenericObject::Next.
Referenced by AddPage().
void ObjectAllocator::SetDebugState (bool State)
< Sets the debugging state
Switches on/off the debugging methods.
Returns pointer to free list
Parameters:
[in] State true=enable, false=disable
Definition at line 743 of file ObjectAllocator.cpp.
References _config, and OAConfig::DebugOn_.
unsigned ObjectAllocator::ValidatePages (VALIDATECALLBACK fn) const
Frees all empty pages (extra credit).
Calls the callback fn for each block that is potentially corrupted.
Parameters:
[in] fn The callback function to use on each potentially corrupted block. void (*)(const void *, size_t)
Returns:
The number of pages validated
Definition at line 622 of file ObjectAllocator.cpp.
References _config, _pageList, _stats, OAConfig::DebugOn_, GetDataPtr(), GetFirstHeader(), GetNextHeader(), OAConfig::HBlockInfo_, GenericObject::Next, OAStats::ObjectSize_, OAConfig::ObjectsPerPage_, PAD_PATTERN, and OAConfig::PadBytes_.
Member Data Documentation
OAConfig ObjectAllocator::_config [private]
The configuration options.
Definition at line 407 of file ObjectAllocator.h.
Referenced by AddPage(), DumpMemoryInUse(), FreeEmptyPages(), FreePage(), GetConfig(), GetDataPtr(), GetFirstHeader(), GetNextHeader(), IsEmptyPage_Header(), IsEmptyPage_NoHeader(), SetDebugState(), and ValidatePages().
GenericObject* ObjectAllocator::_freeList [private]
The free list.
Definition at line 410 of file ObjectAllocator.h.
Referenced by DumpMemoryInUse(), FreePage(), GetFreeList(), IsEmptyPage_NoHeader(), PopFront(), and PushFront().
GenericObject* ObjectAllocator::_pageList [private]
The page list.
Definition at line 411 of file ObjectAllocator.h.
Referenced by DumpMemoryInUse(), FreeEmptyPages(), GetPageList(), ValidatePages(), and ~ObjectAllocator().
OAStats ObjectAllocator::_stats [private]
The current statistics.
Definition at line 408 of file ObjectAllocator.h.
Referenced by AddPage(), DumpMemoryInUse(), FreeEmptyPages(), FreePage(), GetNextHeader(), GetStats(), IsEmptyPage_NoHeader(), PopFront(), PushFront(), and ValidatePages().
const unsigned char ObjectAllocator::ALIGN_PATTERN = 0xEE [static]
Alignment.
Creates the ObjectManager
Definition at line 359 of file ObjectAllocator.h.
Referenced by AddPage().
const unsigned char ObjectAllocator::ALLOCATED_PATTERN = 0xBB [static]
Allocated.
Definition at line 356 of file ObjectAllocator.h.
const unsigned char ObjectAllocator::FREED_PATTERN = 0xCC [static]
Freed.
Definition at line 357 of file ObjectAllocator.h.
const unsigned char ObjectAllocator::PAD_PATTERN = 0xDD [static]
Padding.
Definition at line 358 of file ObjectAllocator.h.
Referenced by AddPage(), and ValidatePages().
const unsigned char ObjectAllocator::UNALLOCATED_PATTERN = 0xAA [static]
Unallocated.
Definition at line 355 of file ObjectAllocator.h.
Referenced by AddPage().
The documentation for this class was generated from the following files:
ObjectAllocator.h
ObjectAllocator.cpp