CS280S14: BList< T, Size > Class Template Reference
BList< T, Size > Class Template Reference
The BList class, which is a doubly linked list with multiple elements per node.
#include <BList.h>
Classes
struct BNode
Each node within the BList.
Public Member Functions
BList ()
default constructor
BList (const BList &rhs)
copy constructor
~BList ()
destructor
BList & operator= (const BList &rhs) throw (BListException)
Pushes the value into the back (list is now unsorted).
void push_back (const T &value) throw (BListException)
Pushes the value into the front (list is now unsorted).
void push_front (const T &value) throw (BListException)
Inserts the value into a sorted list.
void insert (const T &value) throw (BListException)
Removes element at index.
void remove (int index) throw (BListException)
Removes element with value.
void remove_by_value (const T &value)
Returns index of element with value.
int find (const T &value) const
Returns element at index.
T & operator[] (int index) throw (BListException)
Returns element at index (const version).
const T & operator[] (int index) const throw (BListException)
Returns amount of elements.
unsigned size (void) const
Clears entire list.
void clear (void)
Returns the size of a node.
const BNode * GetHead () const
< Returns the head of the list
BListStats GetStats () const
Returns the stats of the list.
Static Public Member Functions
static unsigned nodesize (void)
Returns the size of a node.
Private Member Functions
BNode * _CreateNode (BNode *afterNode=NULL, BNode *beforeNode=NULL) throw (BListException)
< Creates an empty node (new) in between the nodes
void _DeleteNode (BNode *theNode)
Split a node into two, returns pointer to the first node.
BNode * _SplitNode (BNode *theNode)
Split a node into two (creating an extra node), returns pointer to the first node. The elements will also be split across the two nodes.
void _InsertIntoNode (BNode *theNode, size_t pos, const T &theElem)
< Inserts the element into the node
void _RemoveFromNode (BNode *theNode, size_t pos)
Removes the element at the position specified from the node.
int _LinearSearch (BNode *theNode, const T &valToSearch) const
< Linear search for a value in theNode
int _BinarySearch (BNode *theNode, const T &valToSearch) const
Search in the node for the value.
int _FindInNode (BNode *theNode, const T &theVal) const
Search in the node for the value. (Will call LinearSearch if it is not sorted, BinarySearch if it is).
Private Attributes
BNode * head_
points to the first node
BNode * tail_
points to the last node
bool _isSorted
Whether the list is sorted or not.
BListStats _stats
The stats of the BList.
Detailed Description
template<typename T, unsigned Size = 1>
class BList< T, Size >
The BList class, which is a doubly linked list with multiple elements per node.
Definition at line 190 of file BList.h.
Constructor & Destructor Documentation
template<typename T , unsigned Size> BList< T, Size >::BList () [inline]
default constructor
Default constructor for BList.
Definition at line 113 of file BList.cpp.
template<typename T , unsigned Size> BList< T, Size >::BList (const BList< T, Size > & rhs) [inline]
copy constructor
Copy constructor for BList (Deep copy).
Definition at line 123 of file BList.cpp.
References BList< T, Size >::_CreateNode(), BList< T, Size >::_InsertIntoNode(), BList< T, Size >::BList::BNode::count, BList< T, Size >::head_, BList< T, Size >::BList::BNode::next, and BList< T, Size >::BList::BNode::values.
template<typename T , unsigned Size> BList< T, Size >::~BList () [inline]
destructor
Destructor for BList.
Copy assignment (deep copy)
Definition at line 152 of file BList.cpp.
References BList< T, Size >::clear().
Member Function Documentation
template<typename T , unsigned Size> int BList< T, Size >::_BinarySearch (BNode * theNode, const T & valToSearch) const [inline, private]
Search in the node for the value.
Binary search for the value in the list. (Assumed to be sorted).
Parameters:
[in] theNode The node to search in
[in] valToSearch The value to search for
Returns:
The index of the value if it was found, -1 if it wasn't.
Definition at line 823 of file BList.cpp.
References BList< T, Size >::BList::BNode::count, and BList< T, Size >::BList::BNode::values.
Referenced by BList< T, Size >::_FindInNode().
template<typename T , unsigned Size> BList< T, Size >::BNode * BList< T, Size >::_CreateNode (BNode * afterNode = NULL, BNode * beforeNode = NULL) throw (BListException) [inline, private]
< Creates an empty node (new) in between the nodes
Adds an empty node in between afterNode and beforeNode, and returns the new node.
Removes a node (delete)
Parameters:
[in] afterNode The node which will be after the new node
[in] beforeNode The node which will be before the new node
Returns:
The new node
Definition at line 578 of file BList.cpp.
References BListException::E_NO_MEMORY, BList< T, Size >::BList::BNode::next, BList< T, Size >::BList::BNode::prev, and BList< T, Size >::BList::BNode::values.
Referenced by BList< T, Size >::_SplitNode(), and BList< T, Size >::BList().
template<typename T , unsigned Size> void BList< T, Size >::_DeleteNode (BNode * theNode) [inline, private]
Split a node into two, returns pointer to the first node.
Deletes the node and sets up the prev and nexts.
Parameters:
[in] theNode The node to delete
Definition at line 642 of file BList.cpp.
References BList< T, Size >::_stats, BList< T, Size >::head_, BList< T, Size >::BList::BNode::next, BListStats::NodeCount, BList< T, Size >::BList::BNode::prev, and BList< T, Size >::tail_.
Referenced by BList< T, Size >::_RemoveFromNode(), and BList< T, Size >::clear().
template<typename T , unsigned Size> int BList< T, Size >::_FindInNode (BNode * theNode, const T & theVal) const [inline, private]
Search in the node for the value. (Will call LinearSearch if it is not sorted, BinarySearch if it is).
Parameters:
[in] theNode The node to search in
[in] theVal The value to search for
Returns:
The index of the value if it was found, -1 if it wasn't.
Definition at line 769 of file BList.cpp.
References BList< T, Size >::_BinarySearch(), BList< T, Size >::_isSorted, and BList< T, Size >::_LinearSearch().
Referenced by BList< T, Size >::find().
template<typename T , unsigned Size> void BList< T, Size >::_InsertIntoNode (BNode * theNode, size_t pos, const T & theElem) [inline, private]
< Inserts the element into the node
Inserts an element into the node at the position specified.
Removes the element from the node
Parameters:
[in] theNode The node to insert the element into
[in] pos The position to insert the element into
[in] theElem The element to insert
Definition at line 672 of file BList.cpp.
References BList< T, Size >::_stats, BList< T, Size >::BList::BNode::count, BListStats::ItemCount, and BList< T, Size >::BList::BNode::values.
Referenced by BList< T, Size >::_SplitNode(), and BList< T, Size >::BList().
template<typename T , unsigned Size> int BList< T, Size >::_LinearSearch (BNode * theNode, const T & valToSearch) const [inline, private]
< Linear search for a value in theNode
Linear search for the value in the list. (Assumed to be unsorted).
Binary search for a value in theNode
Parameters:
[in] theNode The node to search in
[in] valToSearch The value to search for
Returns:
The index of the value if it was found, -1 if it wasn't.
Definition at line 794 of file BList.cpp.
References BList< T, Size >::BList::BNode::count, and BList< T, Size >::BList::BNode::values.
Referenced by BList< T, Size >::_FindInNode().
template<typename T , unsigned Size> void BList< T, Size >::_RemoveFromNode (BNode * theNode, size_t pos) [inline, private]
Removes the element at the position specified from the node.
Parameters:
[in] theNode The node to remove the element from
[in] pos The position which contains the element to remove
Definition at line 701 of file BList.cpp.
References BList< T, Size >::_DeleteNode(), BList< T, Size >::_stats, BList< T, Size >::BList::BNode::count, BListStats::ItemCount, and BList< T, Size >::BList::BNode::values.
template<typename T , unsigned Size> BList< T, Size >::BNode * BList< T, Size >::_SplitNode (BNode * theNode) [inline, private]
Split a node into two (creating an extra node), returns pointer to the first node. The elements will also be split across the two nodes.
Parameters:
[in] theNode The node to split
Returns:
The original node
Definition at line 732 of file BList.cpp.
References BList< T, Size >::_CreateNode(), BList< T, Size >::_InsertIntoNode(), BList< T, Size >::_stats, BList< T, Size >::BList::BNode::count, BListStats::ItemCount, BList< T, Size >::BList::BNode::next, and BList< T, Size >::BList::BNode::values.
template<typename T , unsigned Size> void BList< T, Size >::clear (void) [inline]
Returns the size of a node.
Deletes all the nodes in the BList.
Definition at line 519 of file BList.cpp.
References BList< T, Size >::_DeleteNode(), BList< T, Size >::_stats, BList< T, Size >::head_, BListStats::ItemCount, and BListStats::NodeCount.
Referenced by BList< T, Size >::~BList().
template<typename T , unsigned Size> int BList< T, Size >::find (const T & value) const [inline]
Returns element at index.
Finds the index at which the element with the value is located.
Parameters:
[in] value The value to search for
Returns:
The index if it could find the element, -1 if it couldn't
Definition at line 399 of file BList.cpp.
References BList< T, Size >::_FindInNode(), BList< T, Size >::_isSorted, BList< T, Size >::BList::BNode::count, BList< T, Size >::head_, BList< T, Size >::BList::BNode::next, and BList< T, Size >::BList::BNode::values.
Referenced by BList< T, Size >::remove_by_value().
template<typename T , unsigned Size> const BList< T, Size >::BNode * BList< T, Size >::GetHead () const [inline]
< Returns the head of the list
Returns the head of the list.
Returns the stats
Returns:
The first element in the list
Definition at line 538 of file BList.cpp.
References BList< T, Size >::head_.
template<typename T , unsigned Size> BListStats BList< T, Size >::GetStats () const [inline]
Returns the stats of the list.
Returns:
The stats of the list
Definition at line 554 of file BList.cpp.
References BList< T, Size >::_stats.
template<typename T , unsigned Size> void BList< T, Size >::insert (const T & value) throw (BListException) [inline]
Removes element at index.
Inserts the value into the BList at the appropriate location. (Assumes the BList is sorted).
Parameters:
[in] value The value to insert
Definition at line 286 of file BList.cpp.
References BList< T, Size >::BList::BNode::count, BList< T, Size >::BList::BNode::next, BList< T, Size >::BList::BNode::prev, and BList< T, Size >::BList::BNode::values.
template<typename T , unsigned Size> unsigned BList< T, Size >::nodesize (void) [inline, static]
Returns the size of a node.
Returns:
The size of a node
Definition at line 99 of file BList.cpp.
template<typename T , unsigned Size> BList< T, Size > & BList< T, Size >::operator= (const BList< T, Size > & rhs) throw (BListException) [inline]
Pushes the value into the back (list is now unsorted).
Copy assignment, does deep copy of rhs, deletes old elements.
Parameters:
[in] rhs The BList to copy
Returns:
The BList calling the operator
Definition at line 171 of file BList.cpp.
References BList< T, Size >::BList::BNode::count, BList< T, Size >::BList::BNode::next, and BList< T, Size >::BList::BNode::values.
template<typename T , unsigned Size> const T & BList< T, Size >::operator[] (int index) const throw (BListException) [inline]
Returns amount of elements.
Returns the element at the index. (Const version).
Parameters:
[in] index The index to get the element from
Returns:
A const reference to the element
Definition at line 478 of file BList.cpp.
References BList< T, Size >::BList::BNode::count, BListException::E_BAD_INDEX, BList< T, Size >::BList::BNode::next, and BList< T, Size >::BList::BNode::values.
template<typename T , unsigned Size> T & BList< T, Size >::operator[] (int index) throw (BListException) [inline]
Returns element at index (const version).
Returns the element at the index.
Parameters:
[in] index The index to get the element from
Returns:
A reference to the element
Definition at line 459 of file BList.cpp.
template<typename T , unsigned Size> void BList< T, Size >::push_back (const T & value) throw (BListException) [inline]
Pushes the value into the front (list is now unsorted).
Pushes an element into the back of the BList. Note: List will be considered unsorted.
Parameters:
[in] value The value to push in
Definition at line 214 of file BList.cpp.
References BList< T, Size >::BList::BNode::count.
template<typename T , unsigned Size> void BList< T, Size >::push_front (const T & value) throw (BListException) [inline]
Inserts the value into a sorted list.
Pushes an element into the front of the BList. Note: List will be considered unsorted.
Parameters:
[in] value The value to push in
Definition at line 250 of file BList.cpp.
template<typename T , unsigned Size> void BList< T, Size >::remove (int index) throw (BListException) [inline]
Removes element with value.
Removes the element at the index specified.
Parameters:
[in] index The index at which the element to be removed is
Definition at line 351 of file BList.cpp.
References BList< T, Size >::BList::BNode::count, BListException::E_BAD_INDEX, and BList< T, Size >::BList::BNode::next.
template<typename T , unsigned Size> void BList< T, Size >::remove_by_value (const T & value) [inline]
Returns index of element with value.
Removes the element which has the value stated.
Parameters:
[in] value The value to remove
Definition at line 378 of file BList.cpp.
References BList< T, Size >::find().
template<typename T , unsigned Size> unsigned BList< T, Size >::size (void) const [inline]
Clears entire list.
Returns the total number of elements.
Returns:
The total number of elements in the list
Definition at line 506 of file BList.cpp.
References BList< T, Size >::_stats, and BListStats::ItemCount.
Member Data Documentation
template<typename T , unsigned Size = 1> bool BList< T, Size >::_isSorted [private]
Whether the list is sorted or not.
Definition at line 259 of file BList.h.
Referenced by BList< T, Size >::_FindInNode(), and BList< T, Size >::find().
template<typename T , unsigned Size = 1> BListStats BList< T, Size >::_stats [private]
The stats of the BList.
Definition at line 260 of file BList.h.
Referenced by BList< T, Size >::_DeleteNode(), BList< T, Size >::_InsertIntoNode(), BList< T, Size >::_RemoveFromNode(), BList< T, Size >::_SplitNode(), BList< T, Size >::clear(), BList< T, Size >::GetStats(), and BList< T, Size >::size().
template<typename T , unsigned Size = 1> BNode* BList< T, Size >::head_ [private]
points to the first node
Definition at line 253 of file BList.h.
Referenced by BList< T, Size >::_DeleteNode(), BList< T, Size >::BList(), BList< T, Size >::clear(), BList< T, Size >::find(), and BList< T, Size >::GetHead().
template<typename T , unsigned Size = 1> BNode* BList< T, Size >::tail_ [private]
points to the last node
Definition at line 254 of file BList.h.
Referenced by BList< T, Size >::_DeleteNode().
The documentation for this class was generated from the following files:
BList.h
BList.cpp